description: example job

target:
  service: sing
  name: huashanvc1
  workspace_name: gcrllama2ws

code:  
  local_dir: /home/chansingh/cookiecutter-ml-research/amlt_example # path to your code on local machine

environment:
  image: amlt-sing/acpt-rocm5.7_ubuntu20.04_py3.10_pytorch_2.0.1
  setup:
    # working directory is local_dir under code above
    - pip install -r requirements.txt --user # install requirements from file
    # - pip install . # install a package from the local directory


storage:
  data:
    storage_account_name: internblobdl
    container_name: t-chansingh
    mount_dir: /blob_data # path to mount the blob on the remote machine

jobs:
- name: job 1
  process_count_per_node: 1
  
  # sku controls the compute you will use
  # here are some common ones you may use

  # gpu jobs
  # 64G16-MI200-xGMI # 16 MI200 GPUs (each with 64 GB mem)
  # 64G2-MI200-xGMI # 2 MI200 GPUs (each with 64 GB mem)
  sku: 64G2-MI200-xGMI
  command:
  # working directory is local_dir under code above, saves an example txt file into blob
  - echo "Running!" # this is where you would run your python script
  - echo "Succesfully tested on cluster" > /blob_data/test_cluster.txt # saves a file into the blob
  - python example_job_script.py 
  